name: Teste de Performance com K6 na Cloud

on:
  workflow_dispatch:

jobs:
  k6-test:
    name: Executar K6 Cloud
    runs-on: ubuntu-latest

    outputs:
      k6_url: ${{ steps.exibir_url.outputs.k6_url }}

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar K6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/k6-archive-keyring.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Executar teste no K6 Cloud
        id: exibir_url
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: |
          echo "Executando teste de performance no K6 Cloud..."
          output=$(k6 cloud --exit-on-running scripts/teste-basico.js)
          url=$(echo "$output" | grep -oE 'https://[^ ]+')
          echo "::notice title=K6 Cloud::🔗 Resultado: $url"
          echo "$url" > k6-url.txt
          echo "k6_url=$url" >> $GITHUB_OUTPUT

      - name: Publicar URL como artefato
        uses: actions/upload-artifact@v4
        with:
          name: k6-url
          path: k6-url.txt
