name: Teste de Performance com K6 na Cloud

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  k6-test:
    name: Executar K6 Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar K6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/k6-archive-keyring.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Executar teste no K6 Cloud e capturar URL
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: |
          echo "Executando teste de performance no K6 Cloud..."
          output=$(k6 cloud scripts/teste-basico.js | tee /dev/tty)
          url=$(echo "$output" | grep -oE 'https://[^ ]+')
          echo "::notice title=K6 Cloud::🔗 Resultado: $url"
